# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Writers Zone
description: > # this means to ignore newlines until "baseurl:"
  Gem Theme for Jekyll based on the
  (official theme minima by Parker Moore)
  with some plugins installed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#Author
author: StartZeroGnu
email: test@email.com
twitter_username: testTwitter
github_username:  testGitHub

# Build settings
markdown: kramdown

theme: writers-zone

exclude:
  - Gemfile
  - Gemfile.lock

#Plugins
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Gist
gist:
  noscript: false

# Paginate
paginate: 3
paginate_path: /page:num/

# SEO (basic config)
#
# Advanced configs https://github.com/jekyll/jekyll-seo-tag#advanced-usage
twitter:
  username: SeoTwitt # twitter site

facebook:
  app_id: test-id
  publisher: test-publisher
  admins: test-admins
