# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Test
email: test@email.com
description: > # this means to ignore newlines until "baseurl:"
  Gem Theme for Jekyll (3.2.1) based
  on the official theme minima (1.2) by Parker Moore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: testTwitter
github_username:  testGitHub

exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown
theme: writers-zone

# Plugins
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Feed
feed:
  path: atom.xml

# Gist
gist:
  noscript: false

# Paginate
paginate: 3
paginate_path: /page:num/
